import fs from 'node:fs';
import { EdgeTTS } from 'node-edge-tts';
import { PassThrough } from 'node:stream';

// Monkey-patch fs.createWriteStream to support in-memory buffers
// This prevents node-edge-tts from saving to disk while avoiding race conditions
const originalCreateWriteStream = fs.createWriteStream;
const buffersMap = new Map();

fs.createWriteStream = (path, options) => {
  if (typeof path === 'string' && path.startsWith('memory_stream_')) {
    const passThrough = new PassThrough();
    const chunks = [];
    passThrough.on('data', chunk => chunks.push(chunk));
    passThrough.on('finish', () => {
      buffersMap.set(path, Buffer.concat(chunks));
    });
    return passThrough;
  }
  return originalCreateWriteStream(path, options);
};

/**
 * Generate audio (TTS) using Microsoft Edge TTS.
 * @param {string} text - The text to be converted to speech.
 * @returns {Promise<Object>} An object containing the audio base64 data and mimeType.
 */
export async function generateSpeech(text) {
  try {
    // Remove emojis from the text so the TTS engine doesn't try to read them
    // Also remove markdown asterisks, hashes, and other symbols
    const cleanText = text
      .replace(/[\p{Emoji_Presentation}\p{Extended_Pictographic}]/gu, '')
      .replace(/[*#~_`]/g, '')
      .trim();

    const tts = new EdgeTTS({ 
      voice: 'en-US-GuyNeural',
      lang: 'en-US',
      outputFormat: 'audio-24khz-48kbitrate-mono-mp3'
    });
    
    const uniqueId = `memory_stream_${Date.now()}_${Math.random()}`;
    
    await tts.ttsPromise(cleanText, uniqueId);
    
    const audioBuffer = buffersMap.get(uniqueId);
    buffersMap.delete(uniqueId);
    
    if (!audioBuffer) {
      throw new Error("No audio data generated by Edge TTS");
    }

    return {
      audioBase64: audioBuffer.toString('base64'),
      mimeType: 'audio/mpeg'
    };
  } catch (error) {
    console.error('Error generating Edge TTS speech:', error);
    throw error;
  }
}
